#!/usr/bin/env bash
# Cài / cập nhật OpenMAIC trên VPS: TTS miễn phí (Browser Native) + chỗ gắn clone (VoxCPM) sau.
# Chạy trên VPS (thường qua GitHub Action appleboy/ssh-action).
set -euo pipefail

OPENMAIC_DIR="${OPENMAIC_DIR:-$HOME/openmaic}"
OPENMAIC_DOMAIN="${OPENMAIC_DOMAIN:-openmaic.vietmycollege.com}"
OPENMAIC_PORT="${OPENMAIC_PORT:-3000}"
REPO_URL="${OPENMAIC_REPO:-https://github.com/THU-MAIC/OpenMAIC.git}"
JAVIS_CONTAINER="${JAVIS_CONTAINER:-javis}"
# 1 = build từ source (chuẩn upstream). 0 = thử image community (nhanh hơn, không chính thức).
OPENMAIC_BUILD="${OPENMAIC_BUILD:-1}"

echo "==> OpenMAIC dir: $OPENMAIC_DIR"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: thiếu lệnh $1" >&2
    exit 1
  }
}
need_cmd docker
need_cmd git

# --- Lấy Gemini key: secret env → hoặc từ Javis Models ---
resolve_google_key() {
  if [ -n "${OPENMAIC_GOOGLE_API_KEY:-}" ]; then
    echo "$OPENMAIC_GOOGLE_API_KEY"
    return
  fi
  if [ -n "${GOOGLE_API_KEY:-}" ]; then
    echo "$GOOGLE_API_KEY"
    return
  fi
  if docker ps --format '{{.Names}}' 2>/dev/null | grep -qx "$JAVIS_CONTAINER"; then
    # Key trong settings.json bị Fernet hoá — đọc qua read_settings() của Javis.
    docker exec -w /app "$JAVIS_CONTAINER" python3 - <<'PY' 2>/dev/null || true
from server.config import read_settings
m = (read_settings().get("model") or {})
k = (m.get("gemini_api_key") or "").strip()
if k and not str(k).startswith("enc:"):
    print(k)
PY
  fi
}

KEY="$(resolve_google_key | tr -d '\r' | head -n1 || true)"
if [ -z "${KEY}" ]; then
  echo "ERROR: chưa có GOOGLE/Gemini API key."
  echo "  - Dán key ở Javis → Models → Google Gemini, rồi chạy lại, HOẶC"
  echo "  - Thêm GitHub secret OPENMAIC_GOOGLE_API_KEY rồi chạy workflow Deploy OpenMAIC."
  exit 1
fi
echo "==> Có Gemini/Google API key (ẩn)."

# --- Clone / update source ---
if [ ! -d "$OPENMAIC_DIR/.git" ]; then
  echo "==> Clone OpenMAIC"
  git clone --depth 1 "$REPO_URL" "$OPENMAIC_DIR"
else
  echo "==> Pull OpenMAIC"
  git -C "$OPENMAIC_DIR" fetch --depth 1 origin main || true
  git -C "$OPENMAIC_DIR" reset --hard origin/main || true
fi

# --- .env.local (free TTS profile) ---
ENV_FILE="$OPENMAIC_DIR/.env.local"
echo "==> Write $ENV_FILE (free TTS + Gemini)"
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/vps-deploy-openmaic.sh — do not commit
GOOGLE_API_KEY=${KEY}
DEFAULT_PROVIDER=google
DEFAULT_MODEL=google:gemini-2.5-flash
TTS_BROWSER_NATIVE_ENABLED=true
TTS_OPENAI_ENABLED=false
NODE_ENV=production
PORT=3000
EOF

# Giữ VoxCPM URL nếu đã cấu hình tay trước đó
if [ -n "${TTS_VOXCPM_BASE_URL:-}" ]; then
  echo "TTS_VOXCPM_BASE_URL=${TTS_VOXCPM_BASE_URL}" >> "$ENV_FILE"
  echo "==> VoxCPM clone URL đã gắn: $TTS_VOXCPM_BASE_URL"
else
  echo "# TTS_VOXCPM_BASE_URL=http://127.0.0.1:8000/v1" >> "$ENV_FILE"
  echo "==> Clone giọng: chưa bật (cần GPU/VoxCPM). Dùng Browser Native trước."
fi

cd "$OPENMAIC_DIR"

if [ "$OPENMAIC_BUILD" = "1" ]; then
  echo "==> docker compose build (có thể 15–40 phút lần đầu)"
  export ALPINE_MIRROR="${ALPINE_MIRROR:-}"
  export NPM_REGISTRY="${NPM_REGISTRY:-}"
  docker compose build
  docker compose up -d
else
  echo "==> Dùng image community (không chính thức)"
  docker pull devprincekumar/openmaic:latest
  docker rm -f openmaic 2>/dev/null || true
  docker run -d --name openmaic --restart unless-stopped \
    -p "${OPENMAIC_PORT}:3000" \
    --env-file "$ENV_FILE" \
    -v openmaic-data:/app/data \
    devprincekumar/openmaic:latest
fi

echo "==> Chờ health"
ok=0
for i in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${OPENMAIC_PORT}/api/health" >/tmp/openmaic-health.json 2>/dev/null; then
    ok=1
    break
  fi
  sleep 5
done
if [ "$ok" != 1 ]; then
  echo "ERROR: /api/health không lên sau ~5 phút. Xem: docker logs openmaic --tail 80"
  docker ps -a --filter name=openmaic || true
  exit 1
fi
echo "==> Health OK:"
cat /tmp/openmaic-health.json
echo

# --- Nginx subdomain (nếu có nginx) ---
if command -v nginx >/dev/null 2>&1; then
  echo "==> Cấu hình nginx $OPENMAIC_DOMAIN → 127.0.0.1:${OPENMAIC_PORT}"
  cat > /etc/nginx/sites-available/openmaic <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${OPENMAIC_DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        proxy_pass http://127.0.0.1:${OPENMAIC_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        client_max_body_size 100m;
    }
}
EOF
  ln -sfn /etc/nginx/sites-available/openmaic /etc/nginx/sites-enabled/openmaic
  nginx -t && systemctl reload nginx
  if command -v certbot >/dev/null 2>&1; then
    if getent hosts "$OPENMAIC_DOMAIN" >/dev/null 2>&1; then
      certbot --nginx -d "$OPENMAIC_DOMAIN" --non-interactive --agree-tos \
        --register-unsafely-without-email --redirect || true
    else
      echo "DNS chưa trỏ $OPENMAIC_DOMAIN → IP VPS. Sau khi DNS OK chạy:"
      echo "  certbot --nginx -d $OPENMAIC_DOMAIN --non-interactive --agree-tos --register-unsafely-without-email --redirect"
    fi
  fi
else
  echo "==> Không có nginx — dùng http://<IP-VPS>:${OPENMAIC_PORT}"
fi

cat <<EOF

==> XONG OpenMAIC (profile miễn phí TTS)
URL nội bộ: http://127.0.0.1:${OPENMAIC_PORT}
Domain:     https://${OPENMAIC_DOMAIN}  (khi DNS + SSL OK)
Hoặc tạm:   http://<IP-VPS>:${OPENMAIC_PORT}

TTS mặc định: Browser Native (Chrome → giọng vi-VN Google, miễn phí)
Clone giọng:  Settings → VoxCPM2 sau khi có TTS_VOXCPM_BASE_URL (GPU)

Trong OpenMAIC: Settings → Text-to-Speech → chọn Browser Native.
Generate classroom: dùng model Gemini đã cấu hình trên server.
EOF
