#!/usr/bin/env bash
# Cài / cập nhật OpenMAIC trên VPS: TTS miễn phí (Browser Native) + chỗ gắn clone (VoxCPM) sau.
# Chạy trên VPS (thường qua GitHub Action appleboy/ssh-action).
set -euo pipefail

OPENMAIC_DIR="${OPENMAIC_DIR:-$HOME/openmaic}"
OPENMAIC_DOMAIN="${OPENMAIC_DOMAIN:-openmaic.vietmycollege.com}"
OPENMAIC_PORT="${OPENMAIC_PORT:-3000}"
REPO_URL="${OPENMAIC_REPO:-https://github.com/THU-MAIC/OpenMAIC.git}"
JAVIS_CONTAINER="${JAVIS_CONTAINER:-javis}"
# 0 = image community (nhanh, phù hợp VPS nhỏ). 1 = build upstream (nặng, dễ OOM).
OPENMAIC_BUILD="${OPENMAIC_BUILD:-0}"
# 1 = không có Gemini key vẫn đưa container lên (TTS Browser Native vẫn dùng được; generate cần key sau).
OPENMAIC_ALLOW_NO_KEY="${OPENMAIC_ALLOW_NO_KEY:-1}"

echo "==> OpenMAIC dir: $OPENMAIC_DIR (BUILD=$OPENMAIC_BUILD)"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: thiếu lệnh $1" >&2
    exit 1
  }
}
need_cmd docker
need_cmd git
if ! command -v curl >/dev/null 2>&1; then
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq curl
  else
    echo "ERROR: cần curl" >&2
    exit 1
  fi
fi

find_javis_container() {
  if docker ps --format '{{.Names}}' | grep -qx "$JAVIS_CONTAINER"; then
    echo "$JAVIS_CONTAINER"
    return
  fi
  # Tên container đôi khi khác (compose project prefix)
  docker ps --format '{{.Names}}' | grep -E '(^|-)javis$' | head -n1 || true
}

# --- Lấy Gemini key: secret env → Javis Models (decrypt) ---
resolve_google_key() {
  if [ -n "${OPENMAIC_GOOGLE_API_KEY:-}" ]; then
    echo "$OPENMAIC_GOOGLE_API_KEY"
    return
  fi
  if [ -n "${GOOGLE_API_KEY:-}" ]; then
    echo "$GOOGLE_API_KEY"
    return
  fi
  local jc
  jc="$(find_javis_container)"
  if [ -z "$jc" ]; then
    echo "==> Không thấy container Javis đang chạy (không lấy được key từ Models)." >&2
    return 0
  fi
  echo "==> Thử đọc gemini_api_key từ container: $jc" >&2
  docker exec -w /app "$jc" python3 - <<'PY' 2>/dev/null || true
from server.config import read_settings
m = (read_settings().get("model") or {})
k = (m.get("gemini_api_key") or "").strip()
if k and not str(k).startswith("enc:"):
    print(k)
else:
    # Chỉ báo có/không — không in secret
    import sys
    print("HAS_KEY=0", file=sys.stderr)
PY
}

KEY="$(resolve_google_key | tr -d '\r' | head -n1 || true)"
# Lọc dòng debug lọt stdout
if [ "$KEY" = "HAS_KEY=0" ]; then KEY=""; fi

if [ -z "${KEY}" ]; then
  echo "WARN: chưa có GOOGLE/Gemini API key."
  echo "  Generate classroom sẽ lỗi cho đến khi có key."
  echo "  Sửa: Javis → Models → Google Gemini, hoặc secret OPENMAIC_GOOGLE_API_KEY, rồi chạy lại."
  if [ "$OPENMAIC_ALLOW_NO_KEY" != "1" ]; then
    exit 1
  fi
  echo "==> Tiếp tục deploy (ALLOW_NO_KEY=1) — TTS Browser Native vẫn dùng được."
else
  echo "==> Có Gemini/Google API key (ẩn)."
fi

# --- Clone / update source (cần cho BUILD=1; BUILD=0 cũng giữ thư mục + .env) ---
if [ ! -d "$OPENMAIC_DIR/.git" ]; then
  echo "==> Clone OpenMAIC"
  mkdir -p "$(dirname "$OPENMAIC_DIR")"
  git clone --depth 1 "$REPO_URL" "$OPENMAIC_DIR"
else
  echo "==> Pull OpenMAIC"
  git -C "$OPENMAIC_DIR" fetch --depth 1 origin main || true
  git -C "$OPENMAIC_DIR" reset --hard origin/main || true
fi

# --- .env.local an toàn (tránh shell inject từ ký tự đặc biệt trong key) ---
ENV_FILE="$OPENMAIC_DIR/.env.local"
echo "==> Write $ENV_FILE (free TTS profile)"
umask 077
export OPENMAIC_DIR
export _OM_KEY="${KEY}"
export _OM_VOX="${TTS_VOXCPM_BASE_URL:-}"
python3 - <<'PY'
import os
from pathlib import Path
key = os.environ.get("_OM_KEY") or ""
vox = os.environ.get("_OM_VOX") or ""
path = Path(os.environ["OPENMAIC_DIR"]) / ".env.local"
lines = [
    "# Generated by scripts/vps-deploy-openmaic.sh — do not commit",
    f"GOOGLE_API_KEY={key}",
    "DEFAULT_PROVIDER=google",
    "DEFAULT_MODEL=google:gemini-2.5-flash",
    "TTS_BROWSER_NATIVE_ENABLED=true",
    "TTS_OPENAI_ENABLED=false",
    "NODE_ENV=production",
    "PORT=3000",
]
if vox:
    lines.append(f"TTS_VOXCPM_BASE_URL={vox}")
else:
    lines.append("# TTS_VOXCPM_BASE_URL=http://127.0.0.1:8000/v1")
path.write_text("\n".join(lines) + "\n", encoding="utf-8")
path.chmod(0o600)
print("wrote", path, "key_len=", len(key))
PY
unset _OM_KEY _OM_VOX

if [ -n "${TTS_VOXCPM_BASE_URL:-}" ]; then
  echo "==> VoxCPM clone URL đã gắn"
else
  echo "==> Clone giọng: chưa bật. Dùng Browser Native trước."
fi

cd "$OPENMAIC_DIR"

# Dừng container cũ cùng cổng nếu có
docker rm -f openmaic 2>/dev/null || true
# Compose project cũ
if [ -f "$OPENMAIC_DIR/docker-compose.yml" ]; then
  (cd "$OPENMAIC_DIR" && docker compose down 2>/dev/null) || true
fi

if [ "$OPENMAIC_BUILD" = "1" ]; then
  echo "==> docker compose build upstream (có thể 15–40 phút, cần RAM lớn)"
  docker compose build
  docker compose up -d openmaic
else
  echo "==> Image community (nhanh) — TTS/LLM qua env .env.local"
  docker pull devprincekumar/openmaic:latest
  docker run -d --name openmaic --restart unless-stopped \
    -p "${OPENMAIC_PORT}:3000" \
    --env-file "$ENV_FILE" \
    -v openmaic_data:/app/data \
    devprincekumar/openmaic:latest
fi

echo "==> Chờ health http://127.0.0.1:${OPENMAIC_PORT}/api/health"
ok=0
for i in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${OPENMAIC_PORT}/api/health" >/tmp/openmaic-health.json 2>/dev/null; then
    ok=1
    break
  fi
  echo "  … chờ ($i/60)"
  sleep 5
done
if [ "$ok" != 1 ]; then
  echo "ERROR: /api/health không lên sau ~5 phút."
  docker ps -a --filter name=openmaic || true
  docker logs openmaic --tail 100 2>/dev/null || true
  # Compose service logs
  (cd "$OPENMAIC_DIR" && docker compose logs --tail 80 openmaic 2>/dev/null) || true
  exit 1
fi
echo "==> Health OK:"
cat /tmp/openmaic-health.json
echo

# --- Nginx subdomain ---
if command -v nginx >/dev/null 2>&1; then
  echo "==> Cấu hình nginx $OPENMAIC_DOMAIN → 127.0.0.1:${OPENMAIC_PORT}"
  cat > /etc/nginx/sites-available/openmaic <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${OPENMAIC_DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        proxy_pass http://127.0.0.1:${OPENMAIC_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        client_max_body_size 100m;
    }
}
EOF
  ln -sfn /etc/nginx/sites-available/openmaic /etc/nginx/sites-enabled/openmaic
  nginx -t && systemctl reload nginx
  if command -v certbot >/dev/null 2>&1; then
    if getent hosts "$OPENMAIC_DOMAIN" >/dev/null 2>&1; then
      certbot --nginx -d "$OPENMAIC_DOMAIN" --non-interactive --agree-tos \
        --register-unsafely-without-email --redirect || true
    else
      echo "DNS chưa trỏ $OPENMAIC_DOMAIN → IP VPS. Sau khi DNS OK chạy:"
      echo "  certbot --nginx -d $OPENMAIC_DOMAIN --non-interactive --agree-tos --register-unsafely-without-email --redirect"
    fi
  fi
else
  echo "==> Không có nginx — dùng http://<IP-VPS>:${OPENMAIC_PORT}"
fi

# Mở firewall cổng 3000 nếu ufw active (truy cập tạm khi chưa có DNS)
if command -v ufw >/dev/null 2>&1; then
  if ufw status 2>/dev/null | grep -qi "Status: active"; then
    ufw allow "${OPENMAIC_PORT}/tcp" comment "openmaic" || true
  fi
fi

cat <<EOF

==> XONG OpenMAIC (profile miễn phí TTS)
URL nội bộ: http://127.0.0.1:${OPENMAIC_PORT}
Domain:     https://${OPENMAIC_DOMAIN}  (khi DNS + SSL OK)
Tạm IP:     http://<IP-VPS>:${OPENMAIC_PORT}

TTS mặc định: Browser Native (Chrome → giọng vi-VN, miễn phí)
Clone giọng:  Settings → VoxCPM2 khi có TTS_VOXCPM_BASE_URL (GPU)
LLM:          Gemini key ${KEY:+đã có}${KEY:-CHƯA có — dán vào Models rồi chạy lại deploy}
EOF
